# Generated by Django 6.0.3 on 2026-03-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsign',
            name='height',
            field=models.FloatField(help_text='Height in meters'),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='weight',
            field=models.FloatField(help_text='Weight in kg'),
        ),
    ]
