# Generated by Django 6.0.3 on 2026-03-03 21:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_labresult_vitalsign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labresult',
            name='normal_range',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='labresult',
            name='notes',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='labresult',
            name='status',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Abnormal', 'Abnormal')], max_length=10),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='test_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='visit_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='patients.patient')),
            ],
        ),
    ]
