# Generated by Django 6.0.3 on 2026-03-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_labresult_normal_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_high_risk',
            field=models.BooleanField(default=False),
        ),
    ]
