# Generated by Django 6.0.3 on 2026-03-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_bed_ward_patient_current_bed_bed_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
